# Generated by dag-tickets release workflow — do not edit by hand.
class DagTickets < Formula
  desc "DAG-aware batch driver for GitHub-issue to PR pipelines"
  homepage "https://github.com/CaicoLeung/dag-tickets"
  license "MIT"
  version "0.3.0"

  on_macos do
    on_arm do
      url "https://github.com/CaicoLeung/dag-tickets/releases/download/v0.3.0/dag-tickets-darwin-arm64.tar.gz"
      sha256 "ea64e010dcd286464923f82f16d179744355ae164e9b6d0c6ae74e929c62efe7"
    end
    on_intel do
      url "https://github.com/CaicoLeung/dag-tickets/releases/download/v0.3.0/dag-tickets-darwin-x64.tar.gz"
      sha256 "daf23c874be39ad46d4d024ac83edc02de950c5b64158498b1919d45e0509963"
    end
  end
  on_linux do
    on_arm do
      url "https://github.com/CaicoLeung/dag-tickets/releases/download/v0.3.0/dag-tickets-linux-arm64.tar.gz"
      sha256 "a761caeb79d84e773220b2b643b5226ea0d5098258fa56124a408c9fb9237151"
    end
    on_intel do
      url "https://github.com/CaicoLeung/dag-tickets/releases/download/v0.3.0/dag-tickets-linux-x64.tar.gz"
      sha256 "e4043839f735f784ca8b8940f6d554e89232727ad16d844bd639c70507bad585"
    end
  end

  def install
    bin.install "dag-tickets"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dag-tickets --version")
  end
end
