# Generated by dag-tickets release workflow — do not edit by hand.
class DagTickets < Formula
  desc "DAG-aware batch driver for GitHub-issue to PR pipelines"
  homepage "https://github.com/CaicoLeung/dag-tickets"
  license "MIT"
  version "0.1.0"

  on_macos do
    on_arm do
      url "https://github.com/CaicoLeung/dag-tickets/releases/download/v0.1.0/dag-tickets-darwin-arm64.tar.gz"
      sha256 "51d5cec5f20d6f69ca9bab1fae83c002b0f115f5766b9049c83ecf4064a86aae"
    end
    on_intel do
      url "https://github.com/CaicoLeung/dag-tickets/releases/download/v0.1.0/dag-tickets-darwin-x64.tar.gz"
      sha256 "b633ac85362b6f4ede7e06f599cb29a310b4f0d72f580c0230167f786788a97e"
    end
  end

  def install
    bin.install "dag-tickets"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/dag-tickets --version")
  end
end
